package main

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"sync"

	"github.com/byuoitav/axis"
	cameraservices "github.com/byuoitav/camera-services"
	"github.com/byuoitav/camera-services/event"
	"github.com/byuoitav/camera-services/handlers"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/spf13/pflag"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

func main() {
	var (
		port     int
		logLevel string

		eventURL string
		name     string
		dnsAddr  string
	)

	pflag.IntVarP(&port, "port", "P", 8080, "port to run the server on")
	pflag.StringVarP(&logLevel, "log-level", "L", "", "level to log at. refer to https://godoc.org/go.uber.org/zap/zapcore#Level for options")
	pflag.StringVar(&eventURL, "event-url", "", "url to send events to")
	pflag.StringVar(&name, "name", "", "the name of this service to include in events generated by it")
	pflag.StringVar(&dnsAddr, "dns-addr", "", "dns server to use for reverse ip lookups")
	pflag.Parse()

	var level zapcore.Level
	if err := level.Set(logLevel); err != nil {
		fmt.Printf("invalid log level: %s\n", err.Error())
		os.Exit(1)
	}

	// build the logger
	config := zap.Config{
		Level:       zap.NewAtomicLevelAt(level),
		Development: false,
		Sampling: &zap.SamplingConfig{
			Initial:    100,
			Thereafter: 100,
		},
		Encoding: "json", EncoderConfig: zapcore.EncoderConfig{
			TimeKey:        "@",
			LevelKey:       "level",
			NameKey:        "logger",
			CallerKey:      "caller",
			MessageKey:     "msg",
			StacktraceKey:  "stacktrace",
			LineEnding:     zapcore.DefaultLineEnding,
			EncodeLevel:    zapcore.LowercaseLevelEncoder,
			EncodeTime:     zapcore.ISO8601TimeEncoder,
			EncodeDuration: zapcore.StringDurationEncoder,
			EncodeCaller:   zapcore.ShortCallerEncoder,
		},
		OutputPaths:      []string{"stderr"},
		ErrorOutputPaths: []string{"stderr"},
	}

	log, err := config.Build()
	if err != nil {
		fmt.Printf("unable to build logger: %s", err)
		os.Exit(1)
	}
	defer func() {
		_ = log.Sync()
	}()

	// validate flags
	if name == "" {
		log.Fatal("--name is required. use --help for more details")
	}

	resolver := &net.Resolver{}
	if len(dnsAddr) > 0 {
		log.Info("Using custom DNS resolver for reserve IP lookups", zap.String("addr", dnsAddr))

		resolver.Dial = func(ctx context.Context, network, address string) (net.Conn, error) {
			dialer := &net.Dialer{}
			return dialer.DialContext(ctx, "udp", dnsAddr)
		}
	}

	cameras := &sync.Map{}
	middleware := handlers.Middleware{
		Logger: log,
	}
	handlers := handlers.CameraController{
		Logger: log,
		// TODO need to make this function better if New() does much of anything (see av-control-api/drivers)
		CreateCamera: func(ctx context.Context, addr string) (cameraservices.Camera, error) {
			if cam, ok := cameras.Load(addr); ok {
				return cam.(*axis.P5414E), nil
			}

			cam := &axis.P5414E{
				Address: addr,
			}

			cameras.Store(addr, cam)
			return cam, nil
		},
		EventPublisher: &event.Publisher{
			GeneratingSystem: name,
			URL:              eventURL,
			Resolver:         resolver,
		},
	}

	r := gin.New()
	r.Use(gin.Recovery())
	r.Use(cors.Default())

	debug := r.Group("/debug")
	debug.GET("/healthz", func(c *gin.Context) {
		c.String(http.StatusOK, "healthy")
	})
	debug.GET("/logz", func(c *gin.Context) {
		c.String(http.StatusOK, config.Level.String())
	})
	debug.GET("/logz/:level", func(c *gin.Context) {
		var level zapcore.Level
		if err := level.Set(c.Param("level")); err != nil {
			c.String(http.StatusBadRequest, err.Error())
			return
		}

		fmt.Printf("***\n\tSetting log level to %s\n***\n", level.String())
		config.Level.SetLevel(level)
		c.String(http.StatusOK, config.Level.String())
	})

	p5414E := r.Group("/v1/P5414-E/:address", middleware.RequestID, middleware.Log, handlers.CameraMiddleware)
	p5414E.GET("/pantilt/up", handlers.Publish("TiltUp"), handlers.TiltUp)
	p5414E.GET("/pantilt/down", handlers.Publish("TiltDown"), handlers.TiltDown)
	p5414E.GET("/pantilt/left", handlers.Publish("PanLeft"), handlers.PanLeft)
	p5414E.GET("/pantilt/right", handlers.Publish("PanRight"), handlers.PanRight)
	p5414E.GET("/pantilt/stop", handlers.Publish("PanTiltStop"), handlers.PanTiltStop)
	p5414E.GET("/zoom/in", handlers.Publish("ZoomIn"), handlers.ZoomIn)
	p5414E.GET("/zoom/out", handlers.Publish("ZoomOut"), handlers.ZoomOut)
	p5414E.GET("/zoom/stop", handlers.Publish("ZoomStop"), handlers.ZoomStop)
	p5414E.GET("/preset/:preset", handlers.Publish("GoToPreset"), handlers.GoToPreset)
	p5414E.GET("/stream", handlers.Publish("Stream"), handlers.Stream)

	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", port))
	if err != nil {
		log.Fatal("unable to bind listener", zap.Error(err))
	}

	log.Info("Starting server", zap.String("on", lis.Addr().String()))
	err = r.RunListener(lis)
	switch {
	case errors.Is(err, http.ErrServerClosed):
	case err != nil:
		log.Fatal("failed to serve", zap.Error(err))
	}
}
