package main

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"sync"

	"github.com/byuoitav/axis"
	cameraservices "github.com/byuoitav/camera-services"
	"github.com/byuoitav/camera-services/event"
	"github.com/byuoitav/camera-services/handlers"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/spf13/pflag"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

func main() {
	var (
		port     int
		logLevel string

		eventURL string
		name     string
		dnsAddr  string
	)

	pflag.IntVarP(&port, "port", "P", 8080, "port to run the server on")
	pflag.StringVarP(&logLevel, "log-level", "L", "", "level to log at. refer to https://godoc.org/go.uber.org/zap/zapcore#Level for options")
	pflag.StringVar(&eventURL, "event-url", "", "url to send events to")
	pflag.StringVar(&name, "name", "", "the name of this service to include in events generated by it")
	pflag.StringVar(&dnsAddr, "dns-addr", "", "dns server to use for reverse ip lookups")
	pflag.Parse()

	var level zapcore.Level
	if err := level.Set(logLevel); err != nil {
		fmt.Printf("invalid log level: %s\n", err.Error())
		os.Exit(1)
	}

	// build the logger
	config := zap.Config{
		Level:       zap.NewAtomicLevelAt(level),
		Development: false,
		Sampling: &zap.SamplingConfig{
			Initial:    100,
			Thereafter: 100,
		},
		Encoding: "json", EncoderConfig: zapcore.EncoderConfig{
			TimeKey:        "@",
			LevelKey:       "level",
			NameKey:        "logger",
			CallerKey:      "caller",
			MessageKey:     "msg",
			StacktraceKey:  "stacktrace",
			LineEnding:     zapcore.DefaultLineEnding,
			EncodeLevel:    zapcore.LowercaseLevelEncoder,
			EncodeTime:     zapcore.ISO8601TimeEncoder,
			EncodeDuration: zapcore.StringDurationEncoder,
			EncodeCaller:   zapcore.ShortCallerEncoder,
		},
		OutputPaths:      []string{"stderr"},
		ErrorOutputPaths: []string{"stderr"},
	}

	log, err := config.Build()
	if err != nil {
		fmt.Printf("unable to build logger: %s", err)
		os.Exit(1)
	}
	defer func() {
		_ = log.Sync()
	}()

	// validate flags
	if name == "" {
		log.Fatal("--name is required. use --help for more details")
	}

	resolver := &net.Resolver{}
	if len(dnsAddr) > 0 {
		log.Info("Using custom DNS resolver for reserve IP lookups", zap.String("addr", dnsAddr))

		resolver.Dial = func(ctx context.Context, network, address string) (net.Conn, error) {
			dialer := &net.Dialer{}
			return dialer.DialContext(ctx, "udp", dnsAddr)
		}
	}

	cameras := &sync.Map{}
	middleware := handlers.Middleware{
		Logger: log,
	}
	p5414EHandlers := handlers.NewCameraController()
	p5414EHandlers.Logger = log
	p5414EHandlers.CreateCamera = func(ctx context.Context, addr string) (cameraservices.Camera, error) {
		// TODO need to make this function better if New() does much of anything (see av-control-api/drivers)
		if cam, ok := cameras.Load(addr); ok {
			if c, ok := cam.(*axis.P5414E); ok {
				return c, nil
			}
		}

		cam := &axis.P5414E{
			Address:       addr,
			StreamProfile: "control",
		}

		cameras.Store(addr, cam)
		return cam, nil
	}
	p5414EHandlers.EventPublisher = &event.Publisher{
		GeneratingSystem: name,
		URL:              eventURL,
		Resolver:         resolver,
	}

	v5915Handlers := handlers.NewCameraController()
	v5915Handlers.Logger = log
	v5915Handlers.CreateCamera = func(ctx context.Context, addr string) (cameraservices.Camera, error) {
		if cam, ok := cameras.Load(addr); ok {
			if c, ok := cam.(*axis.V5915); ok {
				return c, nil
			}
		}

		cam := &axis.V5915{
			Address:       addr,
			StreamProfile: "control",
		}

		cameras.Store(addr, cam)
		return cam, nil
	}
	v5915Handlers.EventPublisher = &event.Publisher{
		GeneratingSystem: name,
		URL:              eventURL,
		Resolver:         resolver,
	}

	r := gin.New()
	r.Use(gin.Recovery())
	r.Use(cors.Default())

	debug := r.Group("/debug")
	debug.GET("/healthz", func(c *gin.Context) {
		c.String(http.StatusOK, "healthy")
	})
	debug.GET("/logz", func(c *gin.Context) {
		c.String(http.StatusOK, config.Level.String())
	})
	debug.GET("/logz/:level", func(c *gin.Context) {
		var level zapcore.Level
		if err := level.Set(c.Param("level")); err != nil {
			c.String(http.StatusBadRequest, err.Error())
			return
		}

		fmt.Printf("***\n\tSetting log level to %s\n***\n", level.String())
		config.Level.SetLevel(level)
		c.String(http.StatusOK, config.Level.String())
	})

	p5414E := r.Group("/v1/P5414-E/:address", middleware.RequestID, middleware.Log, p5414EHandlers.CameraMiddleware)
	p5414E.GET("/pantilt/up", p5414EHandlers.Publish("TiltUp"), p5414EHandlers.TiltUp)
	p5414E.GET("/pantilt/down", p5414EHandlers.Publish("TiltDown"), p5414EHandlers.TiltDown)
	p5414E.GET("/pantilt/left", p5414EHandlers.Publish("PanLeft"), p5414EHandlers.PanLeft)
	p5414E.GET("/pantilt/right", p5414EHandlers.Publish("PanRight"), p5414EHandlers.PanRight)
	p5414E.GET("/pantilt/stop", p5414EHandlers.Publish("PanTiltStop"), p5414EHandlers.PanTiltStop)
	p5414E.GET("/zoom/in", p5414EHandlers.Publish("ZoomIn"), p5414EHandlers.ZoomIn)
	p5414E.GET("/zoom/out", p5414EHandlers.Publish("ZoomOut"), p5414EHandlers.ZoomOut)
	p5414E.GET("/zoom/stop", p5414EHandlers.Publish("ZoomStop"), p5414EHandlers.ZoomStop)
	p5414E.GET("/preset/:preset", p5414EHandlers.Publish("GoToPreset"), p5414EHandlers.GoToPreset)
	p5414E.GET("/stream", p5414EHandlers.Publish("Stream"), p5414EHandlers.Stream)

	v5915 := r.Group("/v1/V5915/:address", middleware.RequestID, middleware.Log, v5915Handlers.CameraMiddleware)
	v5915.GET("/pantilt/up", v5915Handlers.Publish("TiltUp"), v5915Handlers.TiltUp)
	v5915.GET("/pantilt/down", v5915Handlers.Publish("TiltDown"), v5915Handlers.TiltDown)
	v5915.GET("/pantilt/left", v5915Handlers.Publish("PanLeft"), v5915Handlers.PanLeft)
	v5915.GET("/pantilt/right", v5915Handlers.Publish("PanRight"), v5915Handlers.PanRight)
	v5915.GET("/pantilt/stop", v5915Handlers.Publish("PanTiltStop"), v5915Handlers.PanTiltStop)
	v5915.GET("/zoom/in", v5915Handlers.Publish("ZoomIn"), v5915Handlers.ZoomIn)
	v5915.GET("/zoom/out", v5915Handlers.Publish("ZoomOut"), v5915Handlers.ZoomOut)
	v5915.GET("/zoom/stop", v5915Handlers.Publish("ZoomStop"), v5915Handlers.ZoomStop)
	v5915.GET("/preset/:preset", v5915Handlers.Publish("GoToPreset"), v5915Handlers.GoToPreset)
	v5915.GET("/stream", v5915Handlers.Publish("Stream"), v5915Handlers.Stream)

	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", port))
	if err != nil {
		log.Fatal("unable to bind listener", zap.Error(err))
	}

	log.Info("Starting server", zap.String("on", lis.Addr().String()))
	err = r.RunListener(lis)
	switch {
	case errors.Is(err, http.ErrServerClosed):
	case err != nil:
		log.Fatal("failed to serve", zap.Error(err))
	}
}
